// Note: this file is generated by `script/generate-regex.js`
export const abbreviationsInsensitive =
  /^((?:i\.d\.r|ggf|v\.a|z\.b|bzw|u(?:\.\u00E4|sw)|ca)\.|e(?:tc|\.v)\.|gmbh|n(?:ov|[iw])|okt|ju[ln]|s(?:ep|[hlntao])|f(?:eb|r)|d(?:ez|[io])|m(?:ai|[vio])|s(?:td|ek)|jan|m(?:in|[l\u00B2])|m\u00E4r|a(?:ug|pr|g)|rp|h[beh]|b[bewy]|\u00B0c|k[gm]|cm|[ku]g|th|[gm]|l)$/i

export const abbreviationsSensitive =
  /^((?:D(?:ipl\.-Ing|r)|[BM]\.(?:Sc|A)|Prof|Ing)\.)$/

export const specialCharacters =
  /^([\u00C4\u00D6\u00DC\u00DF\u00E4\u00F6\u00FC])$/
