import fs from 'node:fs/promises'
import regexgen from 'regexgen'

// Case-insensitive abbreviation, followed by dot.
const abbreviationsInsensitive = [
  /**
   * # Business and Technical Abbreviations
   */
  'AG', // Aktiengesellschaft
  'GmbH', // Gesellschaft mit beschränkter Haftung
  'UG', // Unternehmergesellschaft
  'KG', // Kommanditgesellschaft
  'e.V.', // Eingetragener Verein
  'usw.', // Und so weiter
  'z.B.', // Zum Beispiel
  'i.d.R.', // In der Regel
  'u.Ä.', // Und Ähnliches
  'bzw.', // Beziehungsweise
  'ca.', // Circa
  'v.a.', // Vor allem
  'ggf.', // Gegebenenfalls
  'etc.', // Et cetera

  /**
   * # Measurements
   */
  'cm', // Centimeter
  'm', // Meter
  'km', // Kilometer
  'g', // Gram
  'kg', // Kilogram
  'l', // Liter
  'ml', // Milliliter
  '°C', // Degree Celsius
  'm²', // Square meter

  /**
   * # Time and Dates
   */
  'sek', // Sekunden
  'min', // Minuten
  'std', // Stunden
  'Mo', // Montag
  'Di', // Dienstag
  'Mi', // Mittwoch
  'Do', // Donnerstag
  'Fr', // Freitag
  'Sa', // Samstag
  'So', // Sonntag
  'Jan', // Januar
  'Feb', // Februar
  'Mär', // März
  'Apr', // April
  'Mai', // Mai
  'Jun', // Juni
  'Jul', // Juli
  'Aug', // August
  'Sep', // September
  'Okt', // Oktober
  'Nov', // November
  'Dez', // Dezember

  /**
   * # Federal States
   */
  'BW', // Baden-Württemberg
  'BY', // Bayern
  'BE', // Berlin
  'BB', // Brandenburg
  'HB', // Bremen
  'HH', // Hamburg
  'HE', // Hessen
  'MV', // Mecklenburg-Vorpommern
  'NI', // Niedersachsen
  'NW', // Nordrhein-Westfalen
  'RP', // Rheinland-Pfalz
  'SL', // Saarland
  'SN', // Sachsen
  'ST', // Sachsen-Anhalt
  'SH', // Schleswig-Holstein
  'TH' // Thüringen
]

// Academic and Professional Titles
const abbreviationsSensitive = [
  'Dr.', // Doktor
  'Prof.', // Professor
  'Ing.', // Ingenieur
  'Dipl.-Ing.', // Diplom-Ingenieur
  'M.Sc.', // Master of Science
  'B.Sc.', // Bachelor of Science
  'M.A.', // Master of Arts
  'B.A.' // Bachelor of Arts
]

// Umlauts and Special Characters
const specialCharacters = ['ä', 'ö', 'ü', 'Ä', 'Ö', 'Ü', 'ß']

await fs.writeFile(
  new URL('../lib/regex.js', import.meta.url),
  [
    '// Note: this file is generated by `script/generate-regex.js`',
    'export const abbreviationsInsensitive =',
    '  /^(' + regexgen(abbreviationsInsensitive).source + ')$/i',
    '',
    'export const abbreviationsSensitive =',
    '  /^(' + regexgen(abbreviationsSensitive).source + ')$/',
    '',
    'export const specialCharacters =',
    '  /^(' + regexgen(specialCharacters).source + ')$/',
    ''
  ].join('\n')
)
